alertmanager:  
  persistentVolume:
    storageClass: nfs-client
    annotations:
     volume.beta.kubernetes.io/storage-class: nfs-client
  ingress:
    enabled: true
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik
    hosts:
    - alertmanager.dijitle.dev

server:
  persistentVolume:
    enabled: true
    storageClass: nfs-client
    size: 16Gi
    annotations:
      volume.beta.kubernetes.io/storage-class: nfs-client
  retention: 7d
  ingress:
    enabled: true
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik
    hosts:
    - prometheus.dijitle.dev

pushgateway:
  ingress:
    enabled: true
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik
    hosts:
    - pushgateway.dijitle.dev

kube-state-metrics:
  image: 
    repository: "carlosedp/kube-state-metrics"
    tag: "v1.9.5"

nodeExporter:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"


extraScrapeConfigs: |
  - job_name: 'weave'
    kubernetes_sd_configs:
    - api_server:
      role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_pod_label_name]
      action: keep
      regex: ^kube-system;weave-net$
    - source_labels: [__meta_kubernetes_pod_container_name,__address__]
      action: replace
      target_label: __address__
      regex: ^weave;(.+?)(?::\d+)?$
      replacement: $1:6782
    - source_labels: [__meta_kubernetes_pod_container_name,__address__]
      action: replace
      target_label: __address__
      regex: ^weave-npc;(.+?)(?::\d+)?$
      replacement: $1:6781
    - source_labels: [__meta_kubernetes_pod_container_name]
      action: replace
      target_label: job
  - job_name: 'drone'
    bearer_token: ...
    static_configs:
    - targets: ['drone.drone.svc.cluster.local']
      
      
# helm upgrade -i prometheus stable/prometheus -n monitoring -f .\charts\prometheus\values.yaml