alertmanager:  
  persistentVolume:
    storageClass: nfs-client
    annotations:
     volume.beta.kubernetes.io/storage-class: nfs-client
  ingress:
    enabled: true
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik
    hosts:
    - alertmanager.dijitle.dev

server:
  extraFlags:
    - storage.tsdb.no-lockfile
  persistentVolume:
    storageClass: nfs-client
    annotations:
      volume.beta.kubernetes.io/storage-class: nfs-client
  ingress:
    enabled: true
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik
    hosts:
    - prometheus.dijitle.dev

pushgateway:
  ingress:
    enabled: true
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
      kubernetes.io/ingress.class: traefik
    hosts:
    - pushgateway.dijitle.dev

kubeStateMetrics:
  image: 
    repository: carlosedp/kube-state-metrics
    tag: v1.7.2

nodeExporter:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"


extraScrapeConfigs: |
  - job_name: 'weave'
    kubernetes_sd_configs:
    - api_server:
      role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_pod_label_name]
      action: keep
      regex: ^kube-system;weave-net$
    - source_labels: [__meta_kubernetes_pod_container_name,__address__]
      action: replace
      target_label: __address__
      regex: ^weave;(.+?)(?::\d+)?$
      replacement: $1:6782
    - source_labels: [__meta_kubernetes_pod_container_name,__address__]
      action: replace
      target_label: __address__
      regex: ^weave-npc;(.+?)(?::\d+)?$
      replacement: $1:6781
    - source_labels: [__meta_kubernetes_pod_container_name]
      action: replace
      target_label: job
      
# helm upgrade -i prometheus stable/prometheus -n kube-system -f values.yaml