kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:2.1.3
          readinessProbe:
            httpGet:
                path: /ping
                port: "admin"
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
                path: /ping
                port: "admin"
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          args:
            - --api
            - --api.insecure
            - --accesslog
            - --accesslog.format=json
            - --providers.kubernetescrd
            - --providers.kubernetesingress
            - --metrics
            - --metrics.prometheus
            - --log
            - --log.format=json
            - --entryPoints.web.address=:80
            - --ping
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080