apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik.dijitle.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-dashboard
          servicePort: 80