apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
      nodePort: 30330
  type: NodePort
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8080  
  type: ClusterIP
  selector:
    app: traefik