apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: artifactory
  labels:
    app: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss:6.2.0
---
kind: Service
apiVersion: v1
metadata:
  name: artifactory
  namespace: artifactory
spec:
  selector:
    app: artifactory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: artifactory
  namespace: artifactory
spec:
  rules:
  - host: artifactory.dijitle.io
    http:
      paths:
      - path: /
        backend:
          serviceName: artifactory
          servicePort: 80
