apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: teamcity
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.12
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password 
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: teamcity
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3306
