apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:7.1
---
kind: Service
apiVersion: v1
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  rules:
  - host: sonar.dijitle.io
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarqube
          servicePort: 80
